import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { AppProvider } from "./context/SearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full min-h-screen p-2 bg-[var(--bg-color)]`}
      >
        <AppProvider>
          <Header />
          <div className="flex h-full min-h-screen gap-3">
            <Sidebar />
            <main className="flex-1">{children}</main>
          </div>
        </AppProvider>
      </body>
    </html>

  );
}
